name: production

on:
  push:
    branches: [ "main" ]
  # if needed
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # 22.12.0
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.12.0
        cache: 'npm'
   # if have ENV
    # - name: Create env
    #   uses: echo "${{ secrets.ENV_PRODUCTION }}" > .env
    - run: npm ci
    - run: npm run build --if-present
    #test
    # - run: npm test
deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: linuxserver.io
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/test_cicd_vps
            git fetch --all
            git reset --hard origin/main
         # if have env
         #  echo "${{ secrets.ENV_PRODUCTION }}" > .env
            npm ci
            npm run build
            pm2 restart all
            pm2 start npm --name "vite-app" -- run dev