name: production

on:
  push:
    branches: ["main"]
  # If needed
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # Supported Node.js versions

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.12.0
        cache: 'npm'

    # Optional: If you have ENV variables
    # - name: Create env
    #   uses: echo "${{ secrets.ENV_PRODUCTION }}" > .env

    - run: npm ci
    - run: npm run build --if-present
    # Uncomment to run tests
    # - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          password: ${{ secrets.PASSWORD_PROD }}
          port: ${{ secrets.PORT_PROD }}
          script: |
             export NVM_DIR=~/.nvm
             source ~/.nvm/nvm.sh
             cd project/test_cicd_vps
             git fetch --all
             git reset --hard origin/main
             npm i
             npm run build
             pm2 restart all
            # pm2 start npm --name "vite-app" -- run dev
