name: production

on:
  push:
    branches: [ "main" ]
  # if needed
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [22.x]
        # 22.12.0
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.12.0
        cache: 'npm'
   # if have ENV
    # - name: Create env
    #   uses: echo "${{ secrets.ENV_PRODUCTION }}" > .env
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
